appveen/ds-ui-appcenter

src/app/dashboard/services/list/list-ag-grid/list-ag-grid.component.ts

removed ID column extra for schema free and added data column next to ID column in DS listing page

---

src/app/dashboard/services/list/list-ag-grid/list-ag-grid.component.ts
src/app/dashboard/services/list/list.component.html
src/app/dashboard/services/list/list.component.scss
src/app/dashboard/services/list/list.component.ts
src/app/service/common.service.ts

1. added count and page changes
2. error handling for count and skip
tested for schema free to make sure nothing breaks

count and page changes

---

proxy.conf.json
src/app/filemapper/column-mapping-control/column-mapping-control.component.ts
src/app/utils/view-control/array-version/array-version.component.html

1. unable to import secure long text/secure rich text 
2. secure rich text not showing properly in history

Def/def2040 unable to import secure long text/secure rich text 

---

src/app/dashboard/services/list/list-view/list-file-view/list-file-view.component.html
src/app/dashboard/workflow/workflow-list/workflow-ag-grid/ag-grid-cell/file-view/file-view.component.html
src/app/utils/file-view/file-view.component.html
src/app/utils/view-control/view-file/view-file.component.html

DEF2302 is fixed

---

src/app/dashboard/workflow/workflow-list/workflow-ag-grid/ag-grid-filters/ag-grid-filters.component.ts

Def2361 is fixed

---

src/app/dashboard/services/manage/manage.component.ts

Defect DEF2209

---

src/app/dashboard/services/list/list.component.html
src/app/dashboard/services/list/list.component.ts

DEF2077 is fixed

---

src/app/dashboard/dashboard-menu/dashboard-menu.component.html
src/app/dashboard/services/list/list.component.html
src/app/dashboard/services/list/list.component.scss

icons and DEF1801 is fixed

---

src/index.html

DEF1510 is fixed

---

src/app/dashboard/services/view/history/history.component.scss

DEF1670 is fixed

---

src/app/dashboard/services/view/history/history.component.html
src/app/utils/manage-control/relation-type/relation-type.component.ts

 DEF2439 & DEF2436 is fixed

---

src/app/dashboard/services/bulk-update/bulk-update.component.ts
src/app/dashboard/services/manage/manage.component.ts

Defect DEF1664 fixed

---

src/app/dashboard/services/list/list-ag-grid/list-ag-grid.component.ts

DEF2434 is fixed

---

package.json

Updating package for node 18

---

src/app/dashboard/services/list/list-ag-grid/list-ag-grid.component.ts
src/app/utils/manage-control/long-text/long-text.component.html
src/app/utils/manage-control/relation-type/relation-type.component.ts
src/app/utils/manage-control/rich-text/rich-text.component.ts

Defect DEF2449 fixed

---

src/app/dashboard/services/bulk-update/bulk-update.component.ts
src/app/dashboard/services/list/list-ag-grid/list-ag-grid.component.ts
src/app/dashboard/services/manage/manage.component.ts

recent fixes which were in main branch to vNext

---

src/app/dashboard/workflow/workflow-filter/workflow-filter.component.ts

DEF2451 is fixed

---

src/app/dashboard/dashboard-menu/dashboard-menu.component.scss

scrollbar fix

---

src/app/filemapper/filemapper.component.ts

DEF1504 is fixed

---

src/app/dashboard/flows-interaction/flows-interaction.component.html
src/app/dashboard/flows-interaction/flows-interaction.component.ts

infinite scroll fix

---

src/app/dashboard/flows-interaction/flows-interaction-view/flow-node-view/flow-node-view.component.ts

Defect DEF2497 fixed

---

src/app/dashboard/flows-interaction/flows-interaction.component.html
src/app/dashboard/flows-interaction/flows-interaction.component.ts

sorting fix for interactions

---

src/app/dashboard/flows-interaction/flows-interaction.component.html
src/app/dashboard/flows-interaction/flows-interaction.component.scss

Refresh Button implemented

---

src/app/dashboard/flows-interaction/flows-interaction.component.html
src/app/dashboard/flows-interaction/flows-interaction.component.ts

added Clear Filter btn and removed startsWith and endsWith

---

src/app/dashboard/flows-interaction/flows-interaction-view/flow-node-view/flow-node-view.component.html

DEF2506 is fixed

---

src/app/dashboard/flows-interaction/flows-interaction-view/flow-node-view/flow-node-view.component.ts

DEF2507 is fixed

---

src/app/dashboard/dashboard-menu/integration-list/integration-list.component.ts
src/app/dashboard/flows-interaction/flows-interaction-view/flows-interaction-view.component.ts
src/app/dashboard/flows-interaction/flows-interaction.component.ts
src/app/service/common.service.ts

Appcenter permission changes

---

src/app/dashboard/flows-interaction/flows-interaction.module.ts

removing code which causes an error

---

src/app/utils/manage-control/relation-type/relation-type.component.ts

DS-316 - fix

---

src/app/auth/auth.component.html

DS-345 is fixed

---

src/app/dashboard/flows-interaction/flows-interaction.component.html
src/app/dashboard/flows-interaction/flows-interaction.component.scss

button fix in interactions

---

src/app/dashboard/flows-interaction/flows-interaction-view/flows-interaction-view.component.ts
src/app/dashboard/flows-interaction/flows-interaction.component.ts
src/app/dashboard/flows-interaction/flows-interaction.module.ts

DS-370 is fixed

---

src/app/dashboard/services/list/list-ag-grid/ag-grid-filters/ag-grid-filters.component.ts

Defect DS-435 fixed

---

src/app/utils/manage-control/date-type/date-type.component.ts

Defect DS-436 fixed

---

angular.json
src/app/utils/view-control/view-date/view-date.component.ts

Defect DS-469 fixed
